import { createHash } from "node:crypto";
import { readFile, realpath, stat } from "node:fs/promises";
import { resolve, sep } from "node:path";
import { DEMO, DEMO_ASSETS } from "../src/demo-manifest.js";

export const DEMO_DIRECTORY = "build/demo/librequake-v0.09-beta-lite";
export const DEMO_ARCHIVE = {
  name: "librequake-lite-v0.09-beta.zip",
  url: "https://github.com/lavenderdotpet/LibreQuake/releases/download/v0.09-beta/lite.zip",
  size: 55987573,
  sha256: "428e736b2f01d953e09a08c60bee975bdc4a0ac2219e97fa095c8af41754da83",
};
const notices = [
  "README-IMPORTANT-LICENCE-INFO", "COPYING", "CREDITS", "README.md",
  "freedoom-docs/COPYING.adoc", "freedoom-docs/CREDITS", "freedoom-docs/README.adoc",
  "misc-docs/LibreProgsDeluxe.md", "misc-docs/pop.lmp.md", "misc-docs/COPYING",
];

export function verifyDemoAsset(bytes, spec) {
  if (bytes.byteLength !== spec.size || createHash("sha256").update(bytes).digest("hex") !== spec.sha256) {
    throw new Error(`${spec.name} does not match the pinned LibreQuake demo. Refusing to serve or install it.`);
  }
  return bytes;
}

/** Preserve upstream notices verbatim alongside a description of our derived encounter. */
export async function makeDemoNotice(id1) {
  let text = `Qev's local LibreQuake demo\n\nLibreQuake v0.09-beta Lite: ${DEMO_ARCHIVE.url}\nUpstream source (including qcsrc/): ${DEMO.source}\npop.lmp generator source: https://github.com/MissLavender-LQ/pop.lmp_generator\n\npak0.pak and pak1.pak are unchanged upstream archives.\npak2.pak is generated by Qev's scripts/make-test-encounter.mjs. It reuses\nLibreQuake lq_e0m1 geometry and changes entity placement to one player,\none grunt, and a nearby health pickup. It is not an original Qev arena.\nNo original proprietary Quake assets are included.\n\nThe assets have multiple licenses, including BSD-3-Clause and GPL-2.0-or-later.\nKeep these notices and provide corresponding GPL sources when redistributing.\nThis setup is for a local development demo, not a public release package.\n\n`;
  for (const name of notices) text += `===== Upstream docs/${name} =====\n\n${await readFile(resolve(id1, "docs", name), "utf8")}\n\n`;
  return Buffer.from(text);
}

/** Return only verified bytes, not filenames: later disk changes cannot leak private PAKs. */
export async function readDemoAssets(directory) {
  const base = await realpath(directory);
  const verified = new Map();
  for (const spec of DEMO_ASSETS) {
    const file = await realpath(resolve(base, spec.name));
    if (!file.startsWith(base + sep)) throw new Error("Demo assets cannot be symlinks outside the bundle.");
    const info = await stat(file);
    if (!info.isFile() || info.size !== spec.size) throw new Error(`Missing or incorrect demo asset: ${spec.name}`);
    verified.set(spec.name, verifyDemoAsset(await readFile(file), spec));
  }
  // Nothing is served until the complete bundle AND its license notices pass validation.
  return verified;
}
